# Generated by Django 3.0 on 2023-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='layout',
            name='Description',
            field=models.TextField(max_length=250),
        ),
    ]
