# Generated by Django 3.0 on 2023-07-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_auto_20230710_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=250)),
                ('Price', models.IntegerField()),
                ('ProdImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('Offer', models.BooleanField(default=False)),
            ],
        ),
    ]
